export const INDIAN_STATES_CITIES: Record<string, string[]> = {
  'Madhya Pradesh': [
    'Indore',
    'Bhopal',
    'Gwalior',
    'Jabalpur',
    'Ujjain',
    'Dewas',
    'Sagar',
    'Ratlam',
    'Satna',
    'Rewa',
    'Singrauli',
    'Pithampur',
    'Katni',
    'Burhanpur',
    'Khandwa',
    'Chhindwara',
    'Morena',
    'Bhind',
    'Vidisha',
    'Mandsaur',
    'Neemuch',
    'Sehore',
    'Hoshangabad (Narmadapuram)',
    'Damoh',
    'Khargone',
  ],
  'Maharashtra': [
    'Mumbai',
    'Pune',
    'Nagpur',
    'Thane',
    'Nashik',
    'Chhatrapati Sambhajinagar (Aurangabad)',
    'Navi Mumbai',
    'Solapur',
    'Amravati',
    'Kolhapur',
    'Sangli',
    'Nanded',
    'Jalgaon',
    'Akola',
    'Latur',
    'Dhule',
    'Ahmednagar',
    'Chandrapur',
    'Vasai-Virar',
    'Bhiwandi',
    'Satara',
    'Ratnagiri',
    'Pimpri-Chinchwad',
  ],
  'Gujarat': [
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Junagadh',
    'Gandhinagar',
    'Anand',
    'Navsari',
    'Morbi',
    'Nadiad',
    'Bharuch',
    'Mehsana',
    'Vapi',
    'Ankleshwar',
    'Porbandar',
    'Bhuj',
    'Palanpur',
    'Valsad',
    'Gondal',
  ],
  'Delhi (NCT)': [
    'New Delhi',
    'Central Delhi',
    'East Delhi',
    'North Delhi',
    'North East Delhi',
    'North West Delhi',
    'South Delhi',
    'South East Delhi',
    'South West Delhi',
    'West Delhi',
    'Shahdara',
    'Dwarka',
    'Rohini',
  ],
  'Uttar Pradesh': [
    'Kanpur',
    'Lucknow',
    'Ghaziabad',
    'Agra',
    'Varanasi',
    'Meerut',
    'Prayagraj (Allahabad)',
    'Bareilly',
    'Aligarh',
    'Moradabad',
    'Saharanpur',
    'Gorakhpur',
    'Noida',
    'Greater Noida',
    'Jhansi',
    'Muzaffarnagar',
    'Mathura',
    'Firozabad',
    'Ayodhya',
    'Badaun',
    'Rampur',
    'Shahjahanpur',
    'Farrukhabad',
    'Hapur',
  ],
  'Rajasthan': [
    'Jaipur',
    'Jodhpur',
    'Kota',
    'Bikaner',
    'Ajmer',
    'Udaipur',
    'Bhilwara',
    'Alwar',
    'Sikar',
    'Sri Ganganagar',
    'Pali',
    'Bharatpur',
    'Jhunjhunu',
    'Beawar',
    'Hanumangarh',
    'Chittorgarh',
    'Bhiwadi',
  ],
  'Karnataka': [
    'Bengaluru (Bangalore)',
    'Mysuru (Mysore)',
    'Hubballi-Dharwad',
    'Mangaluru (Mangalore)',
    'Belagavi (Belgaum)',
    'Davanagere',
    'Ballari (Bellary)',
    'Kalaburagi (Gulbarga)',
    'Tumakuru (Tumkur)',
    'Shivamogga (Shimoga)',
    'Raichur',
    'Bidar',
    'Hosapete',
    'Hassan',
    'Udupi',
  ],
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Tiruchirappalli (Trichy)',
    'Salem',
    'Tiruppur',
    'Erode',
    'Tirunelveli',
    'Vellore',
    'Thoothukudi (Tuticorin)',
    'Thanjavur',
    'Dindigul',
    'Ranipet',
    'Sivakasi',
    'Karur',
    'Hosur',
    'Kanchipuram',
  ],
  'Telangana': [
    'Hyderabad',
    'Warangal',
    'Nizamabad',
    'Karimnagar',
    'Ramagundam',
    'Khammam',
    'Mahbubnagar',
    'Nalgonda',
    'Adilabad',
    'Suryapet',
    'Siddipet',
  ],
  'Haryana': [
    'Gurugram (Gurgaon)',
    'Faridabad',
    'Panipat',
    'Ambala',
    'Yamunanagar',
    'Rohtak',
    'Hisar',
    'Karnal',
    'Sonipat',
    'Panchkula',
    'Bahadurgarh',
    'Rewari',
    'Bhiwani',
    'Palwal',
    'Sirsa',
  ],
  'Punjab': [
    'Ludhiana',
    'Amritsar',
    'Jalandhar',
    'Patiala',
    'Bathinda',
    'Mohali (SAS Nagar)',
    'Hoshiarpur',
    'Pathankot',
    'Moga',
    'Phagwara',
    'Khanna',
    'Rupnagar',
    'Barnala',
    'Firozpur',
  ],
  'West Bengal': [
    'Kolkata',
    'Howrah',
    'Durgapur',
    'Asansol',
    'Siliguri',
    'Bardhaman',
    'Malda',
    'Baharampur',
    'Kharagpur',
    'Haldia',
    'Jalpaiguri',
    'Balurghat',
    'Bankura',
    'Habra',
  ],
  'Andhra Pradesh': [
    'Visakhapatnam',
    'Vijayawada',
    'Guntur',
    'Nellore',
    'Kurnool',
    'Kakinada',
    'Tirupati',
    'Rajamahendravaram',
    'Kadapa',
    'Anantapur',
    'Eluru',
    'Vizianagaram',
    'Ongole',
    'Tenali',
  ],
  'Kerala': [
    'Thiruvananthapuram',
    'Kochi (Cochin)',
    'Kozhikode (Calicut)',
    'Thrissur',
    'Kollam',
    'Palakkad',
    'Kannur',
    'Alappuzha',
    'Kottayam',
    'Kasaragod',
    'Malappuram',
    'Pathanamthitta',
  ],
  'Chhattisgarh': [
    'Raipur',
    'Bhilai',
    'Bilaspur',
    'Korba',
    'Rajnandgaon',
    'Durg',
    'Jagdalpur',
    'Raigarh',
    'Ambikapur',
    'Dhamtari',
  ],
  'Odisha': [
    'Bhubaneswar',
    'Cuttack',
    'Rourkela',
    'Berhampur',
    'Sambalpur',
    'Puri',
    'Balasore',
    'Bhadrak',
    'Baripada',
    'Jharsuguda',
  ],
  'Jharkhand': [
    'Ranchi',
    'Jamshedpur',
    'Dhanbad',
    'Bokaro Steel City',
    'Hazaribagh',
    'Deoghar',
    'Giridih',
    'Ramgarh',
    'Phusro',
    'Chaibasa',
  ],
  'Bihar': [
    'Patna',
    'Gaya',
    'Bhagalpur',
    'Muzaffarpur',
    'Purnia',
    'Darbhanga',
    'Bihar Sharif',
    'Arrah',
    'Begusarai',
    'Katihar',
    'Munger',
    'Chhapra',
    'Samastipur',
  ],
  'Uttarakhand': [
    'Dehradun',
    'Haridwar',
    'Roorkee',
    'Haldwani',
    'Rudrapur',
    'Rishikesh',
    'Kashipur',
    'Pithoragarh',
    'Nainital',
    'Almora',
  ],
  'Himachal Pradesh': [
    'Shimla',
    'Solan',
    'Dharamshala',
    'Baddi',
    'Mandi',
    'Kullu',
    'Bilaspur',
    'Hamirpur',
    'Una',
    'Chamba',
  ],
  'Assam': [
    'Guwahati',
    'Silchar',
    'Dibrugarh',
    'Jorhat',
    'Nagaon',
    'Tinsukia',
    'Tezpur',
    'Bongaigaon',
    'Karimganj',
    'Dhubri',
  ],
  'Goa': [
    'Panaji',
    'Margao',
    'Vasco da Gama',
    'Mapusa',
    'Ponda',
    'Bicholim',
  ],
  'Chandigarh': [
    'Chandigarh',
  ],
  'Jammu & Kashmir': [
    'Srinagar',
    'Jammu',
    'Anantnag',
    'Baramulla',
    'Udhampur',
    'Kathua',
    'Sopore',
  ],
  'Puducherry': [
    'Puducherry',
    'Karaikal',
    'Mahe',
    'Yanam',
  ],
  'Tripura': ['Agartala', 'Dharmanagar', 'Udaipur'],
  'Meghalaya': ['Shillong', 'Tura', 'Jowai'],
  'Nagaland': ['Dimapur', 'Kohima', 'Mokokchung'],
  'Manipur': ['Imphal', 'Churachandpur', 'Thoubal'],
  'Arunachal Pradesh': ['Itanagar', 'Naharlagun', 'Pasighat'],
  'Mizoram': ['Aizawl', 'Lunglei'],
  'Sikkim': ['Gangtok', 'Namchi'],
  'Ladakh': ['Leh', 'Kargil'],
  'Andaman & Nicobar Islands': ['Port Blair'],
  'Dadra & Nagar Haveli and Daman & Diu': ['Daman', 'Diu', 'Silvassa'],
  'Lakshadweep': ['Kavaratti'],
};

export const ALL_INDIAN_STATES = Object.keys(INDIAN_STATES_CITIES).sort();
